sudo: required
services:
  - docker
language: php
php:
  - 7.0
install:
  - composer update
script:
  - composer run full-test
after_success:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --no-include-email)
  - docker build -t rzamana/curriculum .
  - travis/docker_push.sh
