language: php
php:
  - 7.0
install:
  - composer install
script:
  - composer run full-test
before_deploy:
  - docker build -t rzamana/curriculum .
  - $(aws ecr get-login --no-include-email)
  - docker tag rzamana/curriculum $DOCKER_ECR_REPO:$TRAVIS_BUILD
  - docker push $DOCKER_ECR_REPO:$TRAVIS_BUILD
  - docker tag rzamana/curriculum $DOCKER_ECR_REPO:latest
  - docker push $DOCKER_ECR_REPO:latest
