<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('RZamana Curriculum')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink([
                'rel' => 'shortcut icon',
                'type' => 'image/vnd.microsoft.icon',
                'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        Rafael Zamana Kineippe
                    </a>
                </div>
                <?php //die($this->myRoute); ?>
                <div class="collapse navbar-collapse">
                    <?= $this->navigation('navigation')->menu()->setUlClass('nav navbar-nav');?>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a href="<?= $this->url(
                                $this->myRoute,
                                [],
                                [
                                        'force_canonical' => true,
                                        'query' => ['lang' => 'pt_BR']
                                ]
                            ) ?>">
                                <img src="/img/pt-br.png" height="12" alt="pt-br" width="18">
                            </a>
                        </li>
                        <li>
                        <a href="<?= $this->url(
                                $this->myRoute,
                                [],
                                [
                                    'force_canonical' => true,
                                    'query' => ['lang' => 'es_ES']
                                ]
                            ) ?>">
                            <img src="/img/es.png" height="12" alt="es" width="18">
                            </a>
                        </li>
                        <li>
                        <a href="<?= $this->url(
                                $this->myRoute,
                                [],
                                [
                                    'force_canonical' => true,
                                    'query' => ['lang' => 'en_US']
                                ]
                            ) ?>">
                            <img src="/img/en.png" height="12" alt="en" width="18">
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer>
                <p>
                    &copy; 2005 - <?= date('Y') ?> by RZKSkill Serviços Administrativos ME LTDA. 
                    <?= $this->translate('All rights reserved.') ?>
                </p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
