<div class="jumbotron">
    <h1 class="text-center"><?= $this->translate('I\'m a developer') ?></h1>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('Bio') ?></h3>
            </div>
            <div class="panel-body">
                <p><?= $this->translate('Full Bio') ?></p>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('Experience') ?></h3>
            </div>
            <div class="panel-body">
                <p></p>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('Education') ?></h3>
            </div>
            <div class="panel-body">
                <p></p>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('Skills') ?></h3>
            </div>
            <div class="panel-body">
                <p></p>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('Accomplish') ?></h3>
            </div>
            <div class="panel-body">
                <p></p>
            </div>
        </div>
    </div>
</div>