<div class="jumbotron">
    <h1 class="text-center"><?= $this->translate('I\'m a developer') ?></h1>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('The Developer') ?></h3>
            </div>
            <div class="panel-body">
                <p>In 2003 I learned about development and web, since then I learned about PHP, HTML, xHTML, ActionScript, Java, and other languages.</p>
                <p>Here you can see what I learned and all my projects (including where I worked)!</p>
                <p><a class="btn btn-success pull-right" href="#" target="_blank">Developer Curriculum &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
