<div class="jumbotron">
    <h1 class="text-center"><?= $this->translate('Welcome to my curriculum') ?></h1>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('The Archer') ?></h3>
            </div>
            <div class="panel-body">
                <p>Since 2015, I became addicted to archery!</p>
                <p>I won several tournaments, and became the 3rd world best on my category</p>
                <p>Here you can see all my acomplish on archery, and know a little about myself!</p>
                <p><a class="btn btn-success pull-right" href="#" target="_blank">Archer Curriculum &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('Twitter') ?></h3>
            </div>
            <div class="panel-body">
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?= $this->translate('The Developer') ?></h3>
            </div>
            <div class="panel-body">
                <p>In 2003 I learned about development and web, since then I learned about PHP, HTML, xHTML, ActionScript, Java, and other languages.</p>
                <p>Here you can see what I learned and all my projects (including where I worked)!</p>
                <p><a class="btn btn-success pull-right" href="<?= $this->url('developer') ?>">Developer Curriculum &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
